<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__choiceitem</name>
   <tag></tag>
   <elementGuidId>1bc30d5a-2825-4329-9fe5-b2ba682814cd</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>中高考选科</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/div[@class=&quot;dashboard-container&quot;]/div[@class=&quot;ant-row-flex ant-row-flex-center dashboard-content&quot;]/ul[@class=&quot;dashboard-item-wrap&quot;]/li[1]/div[@class=&quot;dashboard-panel&quot;]/div[@class=&quot;title am-text-center&quot;]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
