<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_choosePhysical</name>
   <tag></tag>
   <elementGuidId>c16b3c8e-bf88-47a8-b214-604ee1d0a3ca</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chooseIntentionDe active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.0.0.0.1.3.1.0.0.3.$0.0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>物</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recommandBox&quot;)/div[@class=&quot;layer-recommend-main&quot;]/div[@class=&quot;section&quot;]/div[@class=&quot;layer-recommend-content&quot;]/div[@class=&quot;subject-wrapper clearfix&quot;]/div[@class=&quot;am-u-sm-4  am-text-center&quot;]/div[@class=&quot;chooseIntentionDe active&quot;]</value>
   </webElementProperties>
</WebElementEntity>
