<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_answer</name>
   <tag></tag>
   <elementGuidId>f76baa81-a9d6-467e-beba-f94bf2a5f8be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@data-reactid = '.0.0.0.0.0.1.0.0.0.1.1.$1.0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.0.0.0.1.0.0.0.1.1.$1.0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>否</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;swiper-wrap-root&quot;]/div[@class=&quot;easy-swiper-wrapper clearfix&quot;]/div[@class=&quot;swiper-wrap&quot;]/div[@id=&quot;single-card&quot;]/div[@class=&quot;content&quot;]/ul[1]/li[2]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
