<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_biology</name>
   <tag></tag>
   <elementGuidId>3c62ad89-c53d-4b09-bc60-bef10dba046d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-reactid = '.0.0.0.0.0.1.2.1.0.0.0.1.0.1' and (text() = '生物' or . = '生物')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subject-name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.0.0.0.1.2.1.0.0.0.1.0.1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>生物</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftamination&quot;)/div[3]/div[@class=&quot;content-card no-pad-b&quot;]/div[1]/div[@class=&quot;sort-wrapper clearfix&quot;]/div[@class=&quot;clearfix&quot;]/ul[@class=&quot;subject&quot;]/li[1]/div[@class=&quot;subject-name&quot;]</value>
   </webElementProperties>
</WebElementEntity>
